### ISSUE TITLE
servfail of CNAME records at irregular intervals

### ISSUE THREAD

**Issue by tobit6795** [wernerfred/docker-dyndns#2]
after installing successfully and working with two different locations (one fritzbox each) it seems that the CNAME records wont be served at irregular intervals, sometimes it takes 5 minutes to work by itself again.

any suggestions /ideas?

greetz

**Comment by wernerfred** [comment]
Hi, first of all sorry for the late response. Pretty busy time around the holidays.
Can you please explain what the problem is in detail? And pls also provide (anonymous) information about your setup. I am sure we will find a solution to your problem :)

**Comment by tobit6795** [comment]
ich nehme einfach mal an, dass du deutsch sprichst :D also kurz gesagt, werden meine anfragen in unregelmäßigen abständen nicht beantwortet bzw. ich bekomme keine IP.

![Screenshot_20200121_122214](https://user-images.githubusercontent.com/31254099/72801444-cabec300-3c49-11ea-83f3-3ed8b658d96f.png)

so siehts normalerweise aus:

```
; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> kb.HOSTNAME.work
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18040
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;kb.HOSTNAME.work.               IN      A

;; ANSWER SECTION:
kb.HOSTNAME.work.        217     IN      CNAME   home2.HOSTNAME.work.
home2.HOSTNAME.work.     217     IN      CNAME   kb.dyndns.HOSTNAME.work.
kb.dyndns.HOSTNAME.work. 18      IN      A       <IPADDRESS>

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Tue Jan 21 12:23:40 CET 2020
;; MSG SIZE  rcvd: 104
```
so wenn es mal nicht funktioniert:

```
 dig kb.HOSTNAME.work

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> kb.HOSTNAME.work
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 41470
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;kb.HOSTNAME.work.               IN      A

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Tue Jan 21 12:19:16 CET 2020
;; MSG SIZE  rcvd: 44

```
wenn ich in solch einer Situation einen externen DNS anfrage, in dem Fall cloudflare, kommt folgendes dabei raus

```
dig @1.1.1.1 kb.HOSTNAME.work

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> @1.1.1.1 kb.HOSTNAME.work
; (1 server found)

;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 7819
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;kb.HOSTNAME.work.               IN      A

;; ANSWER SECTION:
kb.HOSTNAME.work.        211     IN      CNAME   home2.HOSTNAME.work.
home2.HOSTNAME.work.     211     IN      CNAME   kb.dyndns.HOSTNAME.work.

;; Query time: 33 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Tue Jan 21 12:18:28 CET 2020
;; MSG SIZE  rcvd: 88

```




ich hoffe das hilft irgenwie, wenn du noch andere informationen brauchst, sag bescheid

**Comment by wernerfred** [comment]
Hi, danke für die Info.
Deutsch ist kein Problem. Damit aber alle potentiellen User von Code + Issues profitieren können würde ich eher Englisch bevorzugen.

Was mir spontan noch einfällt ist:
1. In welchem zeitlichem Zyklus updatest du deine dyndns Einträge?
2. Läuft der Container durchgehend oder passiert das nach vorübergehenden Neustarts (z.B. ausgelöst durch Update der Docker Version oder manuelle Anpassungen)?
3. Benutzt du ein Volume um die Bind Files persistent zu speichern?

Hintergrund:
Die API benutzt das tool ```nsupdate``` (Infos hier: https://linux.die.net/man/8/nsupdate) um die Zone upzudaten. Bind erstellt dafür aber eine Journal ```.jnl``` Datei im selben Verzeichnis wie die Zone und schreibt dort die Änderungen rein anstatt sie direkt im Zone File anzupassen (https://ftp.isc.org/www/bind/arm95/Bv9ARM.ch04.html#journal). 
Wenn der Container jetzt neustartet dann ist natürlich das Journal File weg und Bind im Container kennt nur noch das "leere" Zone File. 

Das mit Cloudflare wird am Cache liegen. Die CNAME Einträge sind noch bekannt, die IP kann aber (da Bind ja wohl zu der Zeit ein Problem hat) nicht aufgelöst werden.

**Comment by tobit6795** [comment]
meinst du in welchem wann die fritzbox ein update schickt? das wären 24h wenn ich mich nicht irre...
ansonsten hab ich die selbe ttl genommen wie im readme angegeben. hab sowohl mit als auch ohne volumes zeitweise das ganze laufen lassen. da hab ich keinen unterschied gemerkt. wenn die abfragen nicht mehr funktioniert haben lief der container in jedem fall, und die IPs waren auch in einem zonefile vorzufinden

**Comment by wernerfred** [comment]
Merkwürdig.
Ich selbst lasse die IP per cronjob stündlich updaten, sollte der Container mal neustarten dann ist spätestens nach einer Stunde wieder die IP eingetragen. Wenn dein Container jetzt quasi neustartet (und somit die Zone cleared) dann kommt das nächste Update über die Fritzbox im schlimmsten Fall erst 24h später. In der Zwischenzeit würde das Zone File quasi keine gültige IP ausliefern können.

Für mehr Informationen was schief läuft wäre ein Log ganz hilfreich. Wenn das Problem also wieder auftritt bitte mal mit ```docker exec -it CONTAINERNAME bash``` in den Container verbinden und logs nach Informationen durchsuchen.

Noch eine Frage:
Läuft dein Container bei dir Zuhause (also hinter der dynamischen IP) oder auf einem Server mit public IP?

**Comment by tobit6795** [comment]
läuft alles auf einem vserver mit pubIP. versuche das heute abend mal zu reproduzieren und exportiere die logs. andere frage: ist es möglich damit mail zu betreiben? bzw. einen mx record zu "füllen", hatte versucht einen MX record anzulegen der auf meine dyn-addresse zeigt, das hat leider nicht funktioniert...

**Comment by tobit6795** [comment]
welche logs brauchst du denn? bzw. wo finde ich die innerhalb des containers? und /var/log ist nichts aussagekräftiges

**Comment by wernerfred** [comment]
> ist es möglich damit mail zu betreiben? bzw. einen mx record zu "füllen", hatte versucht einen MX record anzulegen der auf meine dyn-addresse zeigt, das hat leider nicht funktioniert...

Das wird nicht funktionieren. Siehe [RFC 2181](https://tools.ietf.org/html/rfc2181#section-10.3)

>  The domain name used as the value of a NS resource record, or part of
   the value of a MX resource record must not be an alias.

Du kannst also nicht auf einen CNAME record verweisen. Du könntest höchstens mal testen direkt auf die dyndns Adresse zu zeigen welche auf einen A record auflöst.

Bzgl. Logs muss ich selber mal nachschauen die Tage wo die interessanten Stellen sind.

**Comment by tobit6795** [comment]
hi, hab mal über längere zeit verschiedene DNS server benutzt...das urprüngliche problem hat sich durch die verwendung von googles dns neben cloudflare "behoben" (vorher 1. und 2. dns von cloudflare). über mobilfunk ist das problem einfach nicht mehr aufgetreten

**Comment by wernerfred** [comment]
Hi, sorry das so lange kein update kam. Komm einfach nicht dazu. Ich habe allerdings das komplette Repo mit Actions automatisiert, nächster Schritt ist jetzt Logging implementieren (Danke für den Hint)
Schön das es sich jetzt aber geklärt hat und du auch die Lösung mitgeteilt hast.
